In [5]:
import pandas as pd

df = pd.read_parquet("results.parquet")
df

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

# "openpyxl" This used to open excel files
# "pandas" This is used to read and manipulate data in excel files
# "matplotlib" This is used to create visualizations and charts from the data in excel files
# "numpy" This is used for numerical operations and data manipulation in excel files
# "pyarrow" This is used to see Parquet files which are a columnar storage file format used for efficient data processing and storage.

In [30]:
df.loc[df["year"] == 2022, "type"]

173195    Winter
173196    Winter
213793    Winter
213794    Winter
215139    Winter
           ...
308403    Winter
308404    Winter
308405    Winter
308406    Winter
308407    Winter
Name: type, Length: 4744, dtype: str

In [ ]:
df.iloc[[0,1,2]]

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN

In [34]:
df.sort_values(by="year", ascending=False)

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
308361,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Dario Simion,148951,SUI,Switzerland,8.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308386,2022.0,Winter,Cross Country Skiing (Skiing),"30 kilometres Skiathlon, Men (Olympic)",Ján Koristek,148965,SVK,NaN,45.0,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
203177,NaN,NaN,Fencing,"Sabre, Individual, Men (Olympic)",Lóránt Mészáros,95189,HUN,NaN,5.0,False,NaN
203178,NaN,NaN,Fencing,"Sabre, Team, Men (Olympic)",Lóránt Mészáros,95189,HUN,Hungary,4.0,False,NaN
217586,NaN,NaN,Football (Football),"Football, Men (Intercalated)",Georgios Pantos,100811,GRE,Athens,NaN,False,NaN
217587,NaN,NaN,Football (Football),"Football, Men (Intercalated)",Alexandros Kalafatis,100812,GRE,Athens,NaN,False,NaN
271490,NaN,NaN,Diving (Aquatics),"Platform, Men (Intercalated)",Wilhelm Lindgren,127259,SWE,NaN,13.0,False,NaN

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        305807 non-null  float64
 1   type        305807 non-null  str
 2   discipline  308407 non-null  str
 3   event       308408 non-null  str
 4   as          308408 non-null  str
 5   athlete_id  308408 non-null  int64
 6   noc         308407 non-null  str
 7   team        121714 non-null  str
 8   place       283193 non-null  float64
 9   tied        308408 non-null  bool
 10  medal       44139 non-null   str
dtypes: bool(1), float64(2), int64(1), str(7)
memory usage: 46.0 MB

In [49]:
df.loc[df["medal"] == "Gold", ["event",'team']]

                                event             team
40        Singles, Men (Intercalated)              NaN
41      Doubles, Mixed (Intercalated)    Marie Decugis
42        Doubles, Men (Intercalated)   Maurice Germot
48           Doubles, Mixed (Olympic)  Suzanne Lenglen
80        Doubles, Men (Intercalated)      Max Decugis
...                               ...              ...
308139          Team, Mixed (Olympic)              ROC
308141          Team, Mixed (Olympic)              ROC
308290    Giant Slalom, Men (Olympic)              NaN
308326       Relay, Mixed Youth (YOG)         Europe 1
308340       Ski Cross, Men (Olympic)              NaN

[14783 rows x 2 columns]